version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    labels:
      - dependencies
      - go
    groups:
      go-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io*"
          - "sigs.k8s.io/controller-runtime"
      kubernetes-deps:
        patterns:
          - "k8s.io*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    labels:
      - dependencies
      - github_actions
    groups:
      github-actions-deps:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: "/tools/clean"
    schedule:
      interval: weekly
      day: tuesday
    labels:
      - dependencies
      - tools_clean
      - go
    groups:
      tools-clean-deps:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: "/tools/makejwt"
    schedule:
      interval: weekly
      day: tuesday
    labels:
      - dependencies
      - tools_makejwt
      - go
    groups:
      tools-makejwt-deps:
        patterns:
          - "*"
